### ISSUE TITLE
MAP01 exit in Duality doesn't work

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#698]
https://www.doomworld.com/idgames/levels/doom2/Ports/d-f/duality

Exists in 0.9.4 and dev. Give yourself both red keys (and god mode, since there's an invincible cyberdemon) and noclip through the wall in front of you, then press both terminals to open the exit. I don't see any error messages, and `findexits` says none found. It's MBF21 so maybe it's something to do with that.

**Comment by nstlaurent** [comment]
This should fix it
https://github.com/Helion-Engine/Helion/commit/a0eaa0096efd3b25ac0d39ef5574794548b2f612

It's still going to be strange since the exit is transferred through a voodoo closet. It won't mark it until after the switches are pressed to kill the cyber.

**Comment by 72hr** [comment]
I see the exit now, but it still doesn't trigger. The Cyberdemon doesn't explode either, but it doesn't seem like they're linked in testing in other ports.

**Comment by 72hr** [comment]
Nevermind, after debugging a little I see that it was returning early because Mbf21 was disabled. I never toggled that explicitly, so maybe there's a bug out there. I'll investigate that some more.
